### ISSUE TITLE
App crashes on Signup page

### ISSUE THREAD

**Issue by AnimeshVashistha** [i-vishi/shopping-android-app#5]
When adding the user details on sign up page, the app is getting crashed with following error below:
'2022-02-06 20:23:04.600 7268-7268/com.vishalgaur.shoppingapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.vishalgaur.shoppingapp, PID: 7268
    com.google.firebase.firestore.FirebaseFirestoreException: Failed to get document because the client is offline.
        at com.google.firebase.firestore.DocumentReference.lambda$getViaSnapshotListener$1(DocumentReference.java:331)
        at com.google.firebase.firestore.DocumentReference$$Lambda$2.onEvent(Unknown Source:8)
        at com.google.firebase.firestore.DocumentReference.lambda$addSnapshotListenerInternal$2(DocumentReference.java:504)
        at com.google.firebase.firestore.DocumentReference$$Lambda$3.onEvent(Unknown Source:6)
        at com.google.firebase.firestore.core.AsyncEventListener.lambda$onEvent$0(AsyncEventListener.java:42)
        at com.google.firebase.firestore.core.AsyncEventListener$$Lambda$1.run(Unknown Source:6)
        at com.google.firebase.firestore.util.Executors$$Lambda$1.execute(Unknown Source:0)
        at com.google.firebase.firestore.core.AsyncEventListener.onEvent(AsyncEventListener.java:39)
        at com.google.firebase.firestore.core.QueryListener.raiseInitialEvent(QueryListener.java:176)
        at com.google.firebase.firestore.core.QueryListener.onOnlineStateChanged(QueryListener.java:116)
        at com.google.firebase.firestore.core.EventManager.handleOnlineStateChange(EventManager.java:178)
        at com.google.firebase.firestore.core.SyncEngine.handleOnlineStateChange(SyncEngine.java:368)
        at com.google.firebase.firestore.core.MemoryComponentProvider$RemoteStoreCallback.handleOnlineStateChange(MemoryComponentProvider.java:114)
        at com.google.firebase.firestore.remote.RemoteStore$$Lambda$1.handleOnlineStateChange(Unknown Source:2)
        at com.google.firebase.firestore.remote.OnlineStateTracker.setAndBroadcastState(OnlineStateTracker.java:176)
        at com.google.firebase.firestore.remote.OnlineStateTracker.handleWatchStreamFailure(OnlineStateTracker.java:149)
        at com.google.firebase.firestore.remote.RemoteStore.handleWatchStreamClose(RemoteStore.java:481)
        at com.google.firebase.firestore.remote.RemoteStore.access$200(RemoteStore.java:53)
        at com.google.firebase.firestore.remote.RemoteStore$1.onClose(RemoteStore.java:181)
        at com.google.firebase.firestore.remote.AbstractStream.close(AbstractStream.java:344)
        at com.google.firebase.firestore.remote.AbstractStream.handleServerClose(AbstractStream.java:398)
        at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.lambda$onClose$3(AbstractStream.java:151)
        at com.google.firebase.firestore.remote.AbstractStream$StreamObserver$$Lambda$4.run(Unknown Source:4)
        at com.google.firebase.firestore.remote.AbstractStream$CloseGuardedRunner.run(AbstractStream.java:67)
        at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.onClose(AbstractStream.java:137)
        at com.google.firebase.firestore.remote.FirestoreChannel$1.onClose(FirestoreChannel.java:136)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:413)
        at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:721)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:229)
        at java.lang.Thread.run(Thread.java:923)'

**Comment by bendjedoud** [comment]
App Signup page can not registe new user

**Comment by i-vishi** [comment]
@AnimeshVashistha Thanks for pointing it out. It does not include the network check for making API calls as I built this app to learn Android Development. Will fix it ASAP.
